### ISSUE TITLE
cache.get(key, cb) returns null value for err when server is not running

### ISSUE THREAD

**Issue by ZaleskiR** [dowjones/distribucache-redis-store#2]
I get a null value for err if the redis server is not running.
It would help if there was some kind of detail provided.

**Comment by nemtsov** [comment]
You should get that error if you're listening to an `error` event:  `cache.on('error', function (err) { /*...*/ })`. Can you give that a try please?

**Comment by ZaleskiR** [comment]
This is the test case.  The event gets called with the error.  The callback
has null.
This is not clean as the callback is called twice.

function getCacheStatus(cb) {
  var t = Date.now();

  cache.on('error', function (err) {
    console.log("GOT CACHE ERROR IN EVENT");
    cb(err);
  });

  cache.get('health', function (err, value) {
    if (err) {
      console.log("GOT CACHE ERROR IN CB");
      return cb(err);
    }
    cb(null, value + " " + (Date.now() - t) + " ms");
  });
}

**Comment by nemtsov** [comment]
@ZaleskiR can you also send me the config you used to create the cache?

**Comment by ZaleskiR** [comment]
function populateCache(key, cb) {cb(null, "ok"); };
var cache = cacheClient.create("health", {
  staleIn: "15 sec",
  populateIn: "5 sec",
  pausePopulateIn: "1 hour",
  populate: populateCache
});
